# branches to build
branches:
  only:
    - master # develop

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: C:\projects\my_strstr

platform:
  - x64
  - x86

configuration: Debug

install: # by default, all script lines are interpreted as batch

build:
  project: Build/ALL_BUILD.vcxproj

# scripts to run before build
before_build:
  - mkdir Build
  - cd Build
  - echo Running cmake...
  - cmake -G "Visual Studio 14 2015 Win64" ..

after_build:
  - DIR /S C:\ > C:\projects\my_strstr\listdir.log
  - TREE /F C:\ > C:\projects\my_strstr\tree.log
  - 7z a -t7z logs.7z C:\projects\my_strstr\*.log
#  - test\testrun.bat

artifacts:
  - path: logs.7z
    name: ListDir
